# Line length configuration
line-length = 88

lint.fixable = ["ALL"]
lint.select = ["E4", "E7", "E9", "F", "N", "I"]

# Ignore specific rules
lint.ignore = ["N815", "RET504", "D101", "D103", "ANN201"]
